spring:
  application:
    name: mastodon-to-kafka-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
    name: mastodon-to-kafka-service,config-client
