spring:
  application:
    name: elastic-query-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8886
      profile: dev
      name: elastic-query-service
      username: spring_cloud_user
      password: springCloud_Pwd!
  config:
    import: 'configserver:'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html