services:
  config-server:
    image:  rourory/config-server:${SERVICE_VERSION:-latest}
    ports:
      - ${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    networks:
      - ${GLOBAL_NETWORK:-services}
    environment:
      - SERVER_PORT=${CONFIG_SERVER_PORT}

  mastodon-to-kafka-service:
    restart: always
    depends_on:
      - config-server
      - schema-registry
    image: rourory/mastodon-to-kafka-service:${SERVICE_VERSION:-latest}
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/mastodon-to-kafka-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_TOPIC-NAME=mastodon-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - SPRING_CLOUD_CONFIG_URI=http://config-server:${CONFIG_SERVER_PORT}
    networks:
      - ${GLOBAL_NETWORK:-services}

  kafka-to-elastic-service:
    restart: always
    depends_on:
      - config-server
      - schema-registry
    image: rourory/kafka-to-elastic-service:${SERVICE_VERSION:-latest}
    volumes:
      - "./docker-logs:/workspace/kafka-to-elastic-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - SPRING_CLOUD_CONFIG_URI=http://config-server:${CONFIG_SERVER_PORT}
    networks:
      - ${GLOBAL_NETWORK:-services}