spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
      name: kafka-to-elastic-service
      username: spring_cloud_user
      password: springCloud_Pwd!
  config:
    import: 'configserver:'