server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
#          uri: file:///D:\Projects\JavaProjects\cloud_ex\microsorvices-demo\config-server-repository
          uri: https://github.com/rourory/spring-cloud-repo.git
          clone-on-start: true
      fail-fast: true